project:
  type: website

website:
  title: "Business Statistics Resources"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: scratch-paper.qmd
        text: R Scratch Paper

format:
  html:
    theme: cosmo